/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingGui;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AddReading extends javax.swing.JPanel {

    /**
     * Creates new form AddReadin
     */
    DefaultTableModel dtm;
    int preread;
    Object customerid;
    public AddReading(Object cid) {
        initComponents();
        this.customerid=cid;
       Statement st=DBConnection.statementObject();
       String sql1="SELECT * FROM customer WHERE cid="+cid;
       try {
            ResultSet rs=st.executeQuery(sql1);
            rs.next();
            jLabel3.setText(rs.getString("cid"));
            jLabel4.setText(rs.getString("firstname"));
       }catch(Exception e){
           System.out.println("Data not set");
       }     
       String sql2="SELECT final_reading FROM `biiling_info`WHERE cid ="+this.customerid+" ORDER BY `biiling_info`.`final_reading` DESC";
        System.out.println(sql2);
        try {
            ResultSet rs=st.executeQuery(sql2);
            rs.next();
            System.out.println(rs.getInt(1));
             jLabel7.setText(Integer.toString(rs.getInt("final_reading")));
            System.out.println("last reading set");
        } catch (Exception e) {
            System.out.println("last reading not set"+e);
        }
       
       //to display units n status
       dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
       String sql3="SELECT * FROM biiling_info WHERE cid="+cid+" AND status LIKE 'unpaid' ORDER BY `biiling_info`.`final_reading` DESC";
        try {
             ResultSet rs=st.executeQuery(sql3);
        
          while(rs.next()){
              int units=rs.getInt("final_reading")-rs.getInt("pre_reading");
              int price=units*11;
              dtm.addRow(new Object[]{rs.getInt("biid"),rs.getInt("cid"),rs.getDate("date"),rs.getInt("pre_reading"),rs.getInt("final_reading"),units});
          }
            System.out.println("data displayed");
        } catch (Exception e) {
            System.out.println("data not displayed"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Readings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel1.setText("Cid");

        jLabel2.setText("Final Reading");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.jpg"))); // NOI18N
        jButton1.setText("Add Reading");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Biid", "Cid", "Date", "Pre Reading", "Final Reading", "Units"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Name");

        jLabel6.setText("Last Reading");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/showBook.png"))); // NOI18N
        jButton2.setText("Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int finalreading= Integer.parseInt(jTextField2.getText());
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        Date dd=new Date();
        Statement st=DBConnection.statementObject();
        
        String sql1="SELECT final_reading FROM `biiling_info`WHERE cid ="+this.customerid+" ORDER BY `biiling_info`.`final_reading` DESC" ;
        
        try {
            ResultSet rs=st.executeQuery(sql1);
            rs.next();
            System.out.println(rs.getInt(1));
             this.preread=rs.getInt("final_reading");
            System.out.println("data sorted");
        } catch (Exception e) {
            System.out.println(sql1);
            System.out.println("data not sorted"+e);
        }
        

        String sql2="INSERT INTO biiling_info(cid,date,pre_reading,final_reading,status,paidto)VALUES('"+this.customerid+"','"+d.format(dd)+"',"+this.preread+","+finalreading+",'unpaid','')";
        try {
            st.execute(sql2);
            System.out.println("data inserted");
            MainFrame.ChangePanel(new AddReading(this.customerid));
        } catch (Exception e) {
            System.out.println("data not inserted"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainFrame.ChangePanel(new ReadingRecords(this.customerid));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
